language: node_js

node_js:
  - "node"

sudo: false

os:
  - linux

install:
  - npm install

script:
  - npm test
  - eslint lib test

after_success: npm run coverage
after_script:
  - bash <(curl -s https://codecov.io/bash)
