language: node_js

node_js:
  - "node"

sudo: false

os:
  - linux

install:
  - npm install

script:
  - npm run coverage
  - eslint lib test

after_success:
  - bash <(curl -s https://codecov.io/bash)