language: node_js

node_js:
  - "node"

sudo: false

os:
  - linux

install:
  - npm install jest ts-jest eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser

script:
  - npm test
  - npm run lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
